### ISSUE TITLE
Dropout vs Dropout2d i.e. spatial dropout

### ISSUE THREAD

**Issue by kylehiroyasu** [tjiagoM/stochastic-YOLO#2]
Hi, I was adapting your repo to work on a different object detection dataset. I was wondering if there was a particular reason you chose to use normal dropout instead of 2D dropout which would remove entire convolutional filters. Was this a deliberate choice?

**Comment by tjiagoM** [comment]
Hello! There was no particular deliberate reason in this case. It was just one of those decisions made at the beginning of the project which we didn't explore after. 

If you end up exploring that direction I'd love to hear how it goes!
